# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Notifier\Domain\Model\Notification\NotificationMarkedAsUnread:
    exclusion_policy: all
    properties:
        id:
            type: Kreta\Notifier\Domain\Model\Notification\NotificationId
            expose: true
        occurredOn:
            type: DateTimeImmutable
            expose: true
