# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

parameters:
    kreta_core.class_comment: Kreta\Component\Core\Model\Comment
    kreta_core.class_issue: Kreta\Component\Core\Model\Issue
    kreta_core.class_label: Kreta\Component\Core\Model\Label
    kreta_core.class_project: Kreta\Component\Core\Model\Project
    kreta_core.class_participant: Kreta\Component\Core\Model\Participant
    kreta_core.class_resolution: Kreta\Component\Core\Model\Resolution
    kreta_core.class_status: Kreta\Component\Core\Model\Status
    kreta_core.class_user: Kreta\Component\Core\Model\User

    kreta_core.factory_class_comment: Kreta\Component\Core\Factory\BaseFactory
    kreta_core.factory_class_issue: Kreta\Component\Core\Factory\IssueFactory
    kreta_core.factory_class_label: Kreta\Component\Core\Factory\BaseFactory
    kreta_core.factory_class_project: Kreta\Component\Core\Factory\ProjectFactory
    kreta_core.factory_class_participant: Kreta\Component\Core\Factory\ParticipantFactory
    kreta_core.factory_class_resolution: Kreta\Component\Core\Factory\BaseFactory
    kreta_core.factory_class_status: Kreta\Component\Core\Factory\StatusFactory
    kreta_core.factory_class_user: Kreta\Component\Core\Factory\BaseFactory

    kreta_core.repository_class_comment: Kreta\Component\Core\Repository\CommentRepository
    kreta_core.repository_class_issue: Kreta\Component\Core\Repository\IssueRepository
    kreta_core.repository_class_label: Kreta\Component\Core\Repository\LabelRepository
    kreta_core.repository_class_project: Kreta\Component\Core\Repository\ProjectRepository
    kreta_core.repository_class_participant: Kreta\Component\Core\Repository\ParticipantRepository
    kreta_core.repository_class_resolution: Kreta\Component\Core\Repository\ResolutionRepository
    kreta_core.repository_class_status: Kreta\Component\Core\Repository\StatusRepository
    kreta_core.repository_class_user: Kreta\Component\Core\Repository\UserRepository

    kreta_core.security_class_userProvider: Kreta\Bundle\CoreBundle\Security\UserProvider
    kreta_core.security_class_issueVoter: Kreta\Bundle\CoreBundle\Security\Authorization\Voter\IssueVoter
    kreta_core.security_class_projectVoter: Kreta\Bundle\CoreBundle\Security\Authorization\Voter\ProjectVoter

    kreta_core.service_class_issueStateMachine: Kreta\Bundle\CoreBundle\Services\StateMachine\IssueStateMachine
