# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Organization\Model\Organization:
    type: entity
    repositoryClass: Kreta\Component\Organization\Repository\OrganizationRepository
    table: organization
    id:
        id:
            type: string
            generator:
                strategy: UUID
    fields:
        name:
            type: string
            length: 140
        slug:
            type: string
            length: 140
    oneToOne:
        image:
            targetEntity: Kreta\Component\Media\Model\Interfaces\MediaInterface
            joinColumn:
                name: image
                referencedColumnName: id
            cascade: ['persist', 'remove']
    oneToMany:
        projects:
            targetEntity: Kreta\Component\Project\Model\Interfaces\ProjectInterface
            mappedBy: organization
            cascade: ['persist', 'remove']
        participants:
            targetEntity: Kreta\Component\Organization\Model\Interfaces\ParticipantInterface
            mappedBy: organization
            cascade: ['persist', 'remove']
