# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.task_manager.command_handler.add_user:
        class: Kreta\TaskManager\Application\User\AddUserHandler
        arguments:
            - "@kreta.task_manager.repository.user"
        tags:
            -
                name: command_handler
                handles: Kreta\TaskManager\Application\User\AddUserCommand
