# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.task_manager.specification_factory.organization:
        class: Kreta\TaskManager\Infrastructure\Persistence\Doctrine\ORM\Organization\DoctrineORMOrganizationSpecificationFactory

    kreta.task_manager.specification_factory.project:
        class: Kreta\TaskManager\Infrastructure\Persistence\Doctrine\ORM\Project\DoctrineORMProjectSpecificationFactory

    kreta.task_manager.specification_factory.task:
        class: Kreta\TaskManager\Infrastructure\Persistence\Doctrine\ORM\Project\Task\DoctrineORMTaskSpecificationFactory
