# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        mappings:
            FOSOAuthServerBundle:
                mapping: true
                type: xml
                dir: "Resources/config/doctrine"
                prefix: 'FOS\OAuthServerBundle\Entity'
                is_bundle: true
            KretaApiBundle:
                mapping: true
                type: yml
                dir: "Resources/config/doctrine"
                prefix: 'Kreta\Bundle\ApiBundle\Model'
                is_bundle: true
            KretaIssueBundle:
                mapping: true
                type: yml
                dir: "Resources/config/doctrine"
                prefix: 'Kreta\Component\Issue\Model'
            KretaMediaBundle:
                mapping: true
                type: yml
                dir: "Resources/config/doctrine"
                prefix: 'Kreta\Component\Media\Model'
                is_bundle: true
                is_bundle: true
            KretaProjectBundle:
                mapping: true
                type: yml
                dir: "Resources/config/doctrine"
                prefix: 'Kreta\Component\Project\Model'
                is_bundle: true
            KretaUserBundle:
                mapping: true
                type: yml
                dir: "Resources/config/doctrine"
                prefix: 'Kreta\Component\User\Model'
                is_bundle: true
            KretaCommentBundle:
                mapping: true
                type: yml
                dir: "Resources/config/doctrine"
                prefix: 'Kreta\Component\Comment\Model'
                is_bundle: true
            KretaNotificationBundle:
                mapping: true
                type: yml
                dir: "Resources/config/doctrine"
                prefix: 'Kreta\Component\Notification\Model'
                is_bundle: true
            KretaWorkflowBundle:
                mapping: true
                type: yml
                dir: "Resources/config/doctrine"
                prefix: 'Kreta\Component\Workflow\Model'
                is_bundle: true
        resolve_target_entities:
            Kreta\Bundle\ApiBundle\Model\Interfaces\AccessTokenInterface: Kreta\Bundle\ApiBundle\Model\AccessToken
            Kreta\Bundle\ApiBundle\Model\Interfaces\AuthCodeInterface: Kreta\Bundle\ApiBundle\Model\AuthCode
            Kreta\Bundle\ApiBundle\Model\Interfaces\ClientInterface: Kreta\Bundle\ApiBundle\Model\Client
            Kreta\Bundle\ApiBundle\Model\Interfaces\RefreshTokenInterface: Kreta\Bundle\ApiBundle\Model\RefreshToken
            Kreta\Component\Comment\Model\Interfaces\CommentInterface: Kreta\Component\Comment\Model\Comment
            Kreta\Component\Issue\Model\Interfaces\IssueInterface: Kreta\Component\Issue\Model\Issue
            Kreta\Component\Issue\Model\Interfaces\LabelInterface: Kreta\Component\Issue\Model\Label
            Kreta\Component\Media\Model\Interfaces\MediaInterface: Kreta\Component\Media\Model\Media
            Kreta\Component\Project\Model\Interfaces\ProjectInterface: Kreta\Component\Project\Model\Project
            Kreta\Component\Project\Model\Interfaces\ParticipantInterface: Kreta\Component\Project\Model\Participant
            Kreta\Component\Issue\Model\Interfaces\ResolutionInterface: Kreta\Component\Issue\Model\Resolution
            Kreta\Component\Workflow\Model\Interfaces\StatusInterface: Kreta\Component\Workflow\Model\Status
            Kreta\Component\Workflow\Model\Interfaces\StatusTransitionInterface: Kreta\Component\Workflow\Model\StatusTransition
            Kreta\Component\User\Model\Interfaces\UserInterface: Kreta\Component\User\Model\User
            Kreta\Component\Notification\Model\Interfaces\NotificationInterface: Kreta\Component\Notification\Model\Notification
            Kreta\Component\Workflow\Model\Interfaces\WorkflowInterface: Kreta\Component\Workflow\Model\Workflow
            Kreta\Component\VCS\Model\Interfaces\CommitInterface: Kreta\Component\VCS\Model\Commit

