# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        mappings:
            KretaCoreBundle:
                mapping: true
                type: yml
                dir: "Resources/config/doctrine"
#                alias: 'KretaCoreBundle'
                prefix: 'Kreta\Component\Core\Model'
                is_bundle: true
            KretaNotificationBundle:
                mapping: true
                type: yml
                dir: "Resources/config/doctrine"
                prefix: 'Kreta\Component\Notification\Model'
                is_bundle: true
        resolve_target_entities:
            Kreta\Component\Core\Model\Interfaces\CommentInterface: Kreta\Component\Core\Model\Comment
            Kreta\Component\Core\Model\Interfaces\IssueInterface: Kreta\Component\Core\Model\Issue
            Kreta\Component\Core\Model\Interfaces\LabelInterface: Kreta\Component\Core\Model\Label
            Kreta\Component\Core\Model\Interfaces\ProjectInterface: Kreta\Component\Core\Model\Project
            Kreta\Component\Core\Model\Interfaces\ParticipantInterface: Kreta\Component\Core\Model\Participant
            Kreta\Component\Core\Model\Interfaces\ResolutionInterface: Kreta\Component\Core\Model\Resolution
            Kreta\Component\Core\Model\Interfaces\StatusInterface: Kreta\Component\Core\Model\Status
            Kreta\Component\Core\Model\Interfaces\UserInterface: Kreta\Component\Core\Model\User
            Kreta\Component\Notification\Model\Interfaces\NotificationInterface: Kreta\Component\Core\Model\User
