# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

kreta_project:
    type: rest
    resource: '@KretaProjectBundle/Resources/config/routing.yml'

kreta_issue:
    type: rest
    resource: '@KretaIssueBundle/Resources/config/routing.yml'

kreta_comment:
    type: rest
    resource: '@KretaCommentBundle/Resources/config/routing.yml'

kreta_time_tracking:
    type: rest
    resource: '@KretaTimeTrackingBundle/Resources/config/routing.yml'

kreta_vcs:
    type: rest
    resource: '@KretaVCSBundle/Resources/config/routing/routing.yml'

kreta_workflow:
    type: rest
    resource: '@KretaWorkflowBundle/Resources/config/routing.yml'

# Third party libraries/bundles
api_doc:
    resource: '@KretaSimpleApiDocBundle/Resources/config/routing.yml'
    prefix: /doc
