# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# OAuth login
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /oauth-login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /oauth-connect

kreta_user_bitbucket_login:
    pattern: /oauth-login/check-bitbucket

kreta_user_github_login:
    pattern: /oauth-login/check-github
