# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

kreta_web:
    resource: '@KretaWebBundle/Resources/config/routing.yml'
    prefix: /

kreta_api:
    resource: routing_api.yml
    prefix: /api
    
kreta_media_image:
    pattern: /media/image/{name}
    requirements:
        name: ^[\w,\s-]+\.[A-Za-z]{3}$

# Third party libraries/bundles

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_user:
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'

hwi_oauth_login:
    resource: '@HWIOAuthBundle/Resources/config/routing/login.xml'
    prefix: /oauth-login

hwi_oauth_redirect:
    resource: '@HWIOAuthBundle/Resources/config/routing/redirect.xml'
    prefix: /oauth-connect

kreta_user_bitbucket_login:
    pattern: /oauth-login/check-bitbucket

kreta_user_github_login:
    pattern: /oauth-login/check-github

liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
