# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

parameters:
    kreta_workflow.workflow.class: Kreta\Component\Workflow\Model\Workflow
    kreta_workflow.status.class: Kreta\Component\Workflow\Model\Status
    kreta_workflow.status_transition.class: Kreta\Component\Workflow\Model\StatusTransition

    kreta_workflow.factory_status.class: Kreta\Component\Workflow\Factory\StatusFactory
    kreta_workflow.factory_status_transition.class: Kreta\Component\Workflow\Factory\StatusTransitionFactory
    kreta_workflow.factory_workflow.class: Kreta\Component\Workflow\Factory\WorkflowFactory

    kreta_workflow.repository_workflow.class: Kreta\Component\Workflow\Repository\WorkflowRepository
    kreta_workflow.repository_status.class: Kreta\Component\Workflow\Repository\StatusRepository
    kreta_workflow.repository_status_transition.class: Kreta\Component\Workflow\Repository\StatusTransitionRepository

    kreta_workflow.security_workflow_voter.class: Kreta\Bundle\WorkflowBundle\Security\Authorization\Voter\WorkflowVoter
