# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

Kreta\Component\Workflow\Model\Status:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, workflow]
            message: 'A status with identical name is already exist in this workflow'
    properties:
        color:
            - NotBlank: ~
        name:
            - NotBlank: ~
        type:
            - NotBlank: ~

Kreta\Component\Workflow\Model\StatusTransition:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, workflow]
            message: 'A transition with identical name is already exist in this workflow'
    properties:
        name:
            - NotBlank: ~
        state:
            - NotBlank: ~
    getters:
        validState:
            - 'True':
                message: 'The state cannot be an initial state too'

Kreta\Component\Workflow\Model\Workflow:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name]
            message: 'A workflow with identical name is already exists'
    properties:
        name:
            - NotBlank: ~
