# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

version: '2'

services:
    db:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    rabbitmq:
        image: rabbitmq:3.6.5-management
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

    php:
        build: php7-fpm
        ports:
            - 9000:9000
        environment:
            TASK_MANAGER_HOST: ${TASK_MANAGER_HOST}
            IDENTITY_ACCESS_HOST: ${IDENTITY_ACCESS_HOST}
            SYMFONY_ENV: ${SYMFONY_ENV}
        links:
            - db
        volumes:
            - ~/.composer:/root/.composer
            - ../../TaskManager:/var/www/taskmanager
            - ./data/logs/taskmanager:/var/www/taskmanager/var/logs
            - ../../IdentityAccess:/var/www/identityaccess
            - ./data/logs/identityaccess:/var/www/identityaccess/var/logs
            - ../../SharedKernel:/var/www/SharedKernel
            - /var/www/taskmanager/var/cache
            - /var/www/taskmanager/var/sessions
            - /var/www/taskmanager/vendor
            - /var/www/identityaccess/var/cache
            - /var/www/identityaccess/var/sessions
            - /var/www/identityaccess/vendor

    node:
        build: node
        ports:
            - 3000:3000
        volumes:
            - ../../CompositeUi:/var/www/compositeui

    nginx:
        build: nginx
        ports:
            - 80:80
        links:
            - php
            - node
        volumes_from:
            - php
        volumes:
            - ./data/logs/nginx/:/var/log/nginx
