# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

services:
#### HANDLERS ####
    kreta_time_tracking.form_handler.time_entry:
        parent: kreta_core.form_handler.handler
        arguments:
            - kreta_time_tracking_time_entry_type

#### TYPES ####
    kreta_time_tracking.form_type.time_entry:
        class: %kreta_time_tracking.form_type.time_entry.class%
        arguments:
            - %kreta_time_tracking.time_entry.class%
            - @kreta_time_tracking.factory.time_entry
            - @security.context
        tags:
            - { name: form.type, alias: 'kreta_time_tracking_time_entry_type' }
