# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Notifier\Domain\Model\Inbox\Notification\NotificationPublished:
    exclusion_policy: all
    properties:
        userId:
            type: Kreta\Notifier\Domain\Model\Inbox\UserId
            expose: true
        notificationId:
            type: Kreta\Notifier\Domain\Model\Inbox\Notification\NotificationId
            expose: true
        body:
            type: Kreta\Notifier\Domain\Model\Inbox\Notification\NotificationBody
            expose: true
        status:
            type: Kreta\Notifier\Domain\Model\Inbox\Notification\NotificationStatus
            expose: true
        occurredOn:
            type: DateTimeImmutable<'U'>
            expose: true
