# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Project\Model\Project:
    exclusion_policy: ALL
    relations:
        -
            rel: self
            href:
                route: get_project
                parameters:
                    projectId: expr(object.getId())
                absolute: 0
            exclusion:
                groups: [projectList, project]
        -
            rel: projects
            href:
                route: get_projects
                absolute: 0
            exclusion:
                groups: [projectList, project]
        -
            rel: issues
            href:
                route: get_issues
                absolute: 0
            exclusion:
                groups: [projectList, project]
        -
            rel: labels
            href:
                route: get_projects_labels
                parameters:
                    projectId: expr(object.getId())
                absolute: 0
            exclusion:
                groups: [projectList, project]
        -
            rel: issue_priorities
            href:
                route: get_projects_issue_priorities
                parameters:
                    projectId: expr(object.getId())
                absolute: 0
            exclusion:
                groups: [projectList, project]
        -
            rel: organization
            href:
                route: get_organization
                parameters:
                    organizationId: expr(object.getOrganization().getId())
                absolute: 0
            exclusion:
                groups: [projectList, project]
                exclude_if: expr(object.getOrganization() === null)
        -
            rel: workflow
            href:
                route: get_workflow
                parameters:
                    workflowId: expr(object.getWorkflow().getId())
                absolute: 0
            exclusion:
                groups: [projectList, project]
        -
            rel: statuses
            href:
                route: get_workflow_statuses
                parameters:
                    workflowId: expr(object.getWorkflow().getId())
                absolute: 0
            exclusion:
                groups: [projectList, project]
        -
            rel: transitions
            href:
                route: get_workflow_transitions
                parameters:
                    workflowId: expr(object.getWorkflow().getId())
                absolute: 0
            exclusion:
                groups: [projectList, project]
    properties:
        id:
            expose: true
            groups: [projectList, project, projectPrivate, participantList, participant, organizationPrivate]
        image:
            expose: true
            groups: [projectList, project, projectPrivate]
        issues:
            expose: true
            groups: []
        creator:
            expose: true
            groups: []
        labels:
            expose: true
            groups: [projectList, project, projectPrivate]
        name:
            expose: true
            groups: [projectList, project, projectPrivate, participantList, participant, organizationPrivate]
        participants:
            expose: true
            groups: [projectList, project, projectPrivate]
        issuePriorities:
            expose: true
            groups: [projectList, project, projectPrivate]
        organization:
            expose: true
            groups: [projectList, project, projectPrivate]
        slug:
            expose: true
            groups: [projectList, project, projectPrivate, participantList, participant, organizationPrivate]
        statuses:
            expose: true
            groups: []
        workflow:
            expose: true
            groups: [project, projectPrivate]
