# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

ben_gor_user:
    resource: '@BenGorUserBundle/Resources/config/routing/all.yml'

kreta_identity_access_who_am_i:
    path: /user/api
    defaults:
        _controller: "kreta.identity_access.api_rest.controller:whoAmIAction"
    methods:
        - GET
