---
-
    hosts: all
    become: yes
    become_user: root
    become_method: su
    vars_files:
        - parameters.yml
        - vars/mysql.yml
        - vars/php.yml
        - vars/rabbitmq.yml
        - vars/security.yml
        - vars/firewall.yml
        - vars/nginx.yml
    roles:
        - geerlingguy.repo-remi
        - geerlingguy.mysql
        - geerlingguy.nginx
        - geerlingguy.php
        - openstack-ansible-galaxy.rabbitmq
        - geerlingguy.firewall
        - geerlingguy.security
        - geerlingguy.git
        - kbrebanov.unzip
    tasks:
        - include: tasks/users.yml
        - include: tasks/hosts.yml

