# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

kreta_web_homepage:
    path: /
    defaults: { _controller: KretaWebBundle:Default:index }
    methods: [GET]

#### ORGANIZATION ####
kreta_web_organization_show:
    path: /{organizationId}/
    defaults: { _controller: KretaWebBundle:Default:index }
    methods: [GET, PUT]

#### PROJECT ####
kreta_web_project_show:
    path: /{organizationId}/{projectId}/
    defaults: { _controller: KretaWebBundle:Default:index }
    methods: [GET, PUT]

kreta_web_project_new:
    path: /{organizationId}/project/new/
    defaults: { _controller: KretaWebBundle:Default:index }
    methods: [GET, POST]

kreta_web_project_settings:
    path: /{organizationId}/{projectId}/settings/
    defaults: { _controller: KretaWebBundle:Default:index }
    methods: [GET]

#### PROFILE ####
kreta_web_profile:
    path: /profile/
    defaults: { _controller: KretaWebBundle:Default:index }
    methods: [GET, POST]

#### ISSUE ####
kreta_web_issue_new:
    path: /{organizationId}/{projectId}/issue/new/
    defaults: { _controller: KretaWebBundle:Default:index }
    methods: [GET, POST]

kreta_web_issue_show:
    path: /{organizationId}/{projectId}/issue/{issueId}/
    defaults: { _controller: KretaWebBundle:Default:index }
    methods: [GET, PUT]
