# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

services:
#### HANDLERS ####
    kreta_project.form_handler.api.label:
        class: Kreta\Bundle\ProjectBundle\Form\Handler\Api\LabelHandler
        parent: kreta_core.form_handler.abstract
        arguments: [@kreta_project.factory.label]
    kreta_project.form_handler.api.project:
        class: Kreta\Bundle\ProjectBundle\Form\Handler\Api\ProjectHandler
        parent: kreta_core.form_handler.abstract
        arguments: 
            - @kreta_project.uploader.image_project
    kreta_project.form_handler.api.participant:
        class: Kreta\Bundle\ProjectBundle\Form\Handler\Api\ParticipantHandler
        parent: kreta_core.form_handler.abstract
        arguments: [@security.context, @kreta_project.factory.participant, @kreta_user.repository.user]
    kreta_project.form_handler.project:
        class: %kreta_project.form_project_handler.class%
        parent: kreta_core.form_handler.abstract
        arguments: [@kreta_media.factory.media, @kreta_project.uploader.image_project]

#### TYPES ####
    kreta_project.form_type.project:
        class: Kreta\Bundle\ProjectBundle\Form\Type\Api\ProjectType
        arguments:
            - %kreta_project.project.class%
            - @kreta_project.factory.project
            - @doctrine.orm.entity_manager
            - @security.context
        tags:
            - { name: form.type, alias: 'kreta_project_project_type' }
