# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
#### HANDLERS ####
    kreta_project.form_handler.label:
        parent: kreta_core.form_handler.handler
        arguments:
            - Kreta\Component\Project\Form\Type\LabelType
    kreta_project.form_handler.issue_priority:
        parent: kreta_core.form_handler.handler
        arguments:
            - Kreta\Component\Project\Form\Type\PriorityType
    kreta_project.form_handler.project:
        class: %kreta_project.form_handler.project.class%
        parent: kreta_core.form_handler.handler
        arguments:
            - Kreta\Component\Project\Form\Type\ProjectType
            - @kreta_media.factory.media
            - @kreta_project.uploader.image_project
    kreta_project.form_handler.participant:
        parent: kreta_core.form_handler.handler
        arguments:
            - Kreta\Component\Project\Form\Type\ParticipantType

#### TYPES ####
    kreta_project.form_type.label:
        class: %kreta_project.form_type.label.class%
        arguments:
            - %kreta_project.label.class%
            - @kreta_project.factory.label
            - @security.token_storage
        tags:
            - { name: form.type }
    kreta_project.form_type.issue_priority:
        class: %kreta_project.form_type.issue_priority.class%
        arguments:
            - %kreta_project.issue_priority.class%
            - @kreta_project.factory.issue_priority
        tags:
            - { name: form.type }
    kreta_project.form_type.project:
        class: %kreta_project.form_type.project.class%
        arguments:
            - %kreta_project.project.class%
            - @kreta_project.factory.project
            - @security.token_storage
        tags:
            - { name: form.type }
    kreta_project.form_type.participant:
        class: %kreta_project.form_type.participant.class%
        arguments:
            - %kreta_project.participant.class%
            - @kreta_project.factory.participant
            - @security.token_storage
        tags:
            - { name: form.type }
    kreta_project.form_type.role:
        class: %kreta_project.form_type.role.class%
        tags:
            - { name: form.type }
