# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    kreta_project.label.class: Kreta\Component\Project\Model\Label
    kreta_project.participant.class: Kreta\Component\Project\Model\Participant
    kreta_project.issue_priority.class: Kreta\Component\Project\Model\IssuePriority
    kreta_project.project.class: Kreta\Component\Project\Model\Project

    kreta_project.factory_label.class: Kreta\Component\Project\Factory\LabelFactory
    kreta_project.factory_participant.class: Kreta\Component\Project\Factory\ParticipantFactory
    kreta_project.factory_issue_priority.class: Kreta\Component\Project\Factory\IssuePriorityFactory
    kreta_project.factory_project.class: Kreta\Component\Project\Factory\ProjectFactory

    kreta_project.repository_label.class: Kreta\Component\Project\Repository\LabelRepository
    kreta_project.repository_participant.class: Kreta\Component\Project\Repository\ParticipantRepository
    kreta_project.repository_issue_priority.class: Kreta\Component\Project\Repository\IssuePriorityRepository
    kreta_project.repository_project.class: Kreta\Component\Project\Repository\ProjectRepository

    kreta_project.form_handler.project.class: Kreta\Component\Project\Form\Handler\ProjectHandler

    kreta_project.form_type.label.class: Kreta\Component\Project\Form\Type\LabelType
    kreta_project.form_type.participant.class: Kreta\Component\Project\Form\Type\ParticipantType
    kreta_project.form_type.issue_priority.class: Kreta\Component\Project\Form\Type\IssuePriorityType
    kreta_project.form_type.project.class: Kreta\Component\Project\Form\Type\ProjectType
    kreta_project.form_type.role.class: Kreta\Component\Project\Form\Type\RoleType

    kreta_project.security_project_voter.class: Kreta\Bundle\ProjectBundle\Security\Authorization\Voter\ProjectVoter
