# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

parameters:
    kreta_project.label.class: Kreta\Component\Project\Model\Label
    kreta_project.participant.class: Kreta\Component\Project\Model\Participant
    kreta_project.project.class: Kreta\Component\Project\Model\Project

    kreta_project.factory_label.class: Kreta\Component\Project\Factory\LabelFactory
    kreta_project.factory_participant.class: Kreta\Component\Project\Factory\ParticipantFactory
    kreta_project.factory_project.class: Kreta\Component\Project\Factory\ProjectFactory

    kreta_project.repository_label.class: Kreta\Component\Project\Repository\LabelRepository
    kreta_project.repository_participant.class: Kreta\Component\Project\Repository\ParticipantRepository
    kreta_project.repository_project.class: Kreta\Component\Project\Repository\ProjectRepository

    kreta_project.form_handler.project.class: Kreta\Component\Project\Form\Handler\ProjectHandler
    
    kreta_project.form_type.label.class: Kreta\Component\Project\Form\Type\LabelType
    kreta_project.form_type.project.class: Kreta\Component\Project\Form\Type\ProjectType
    kreta_project.form_type.participant.class: Kreta\Component\Project\Form\Type\ParticipantType
    kreta_project.form_type.role.class: Kreta\Component\Project\Form\Type\RoleType

    kreta_project.security_project_voter.class: Kreta\Bundle\ProjectBundle\Security\Authorization\Voter\ProjectVoter
