# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

kreta_api_project:
    type: rest
    resource: Kreta\Bundle\ProjectBundle\Controller\ProjectController

kreta_api_label:
    type: rest
    parent: kreta_api_project
    resource: Kreta\Bundle\ProjectBundle\Controller\LabelController

kreta_api_participant:
    type: rest
    parent: kreta_api_project
    resource: Kreta\Bundle\ProjectBundle\Controller\ParticipantController

kreta_api_issue_priority:
    type: rest
    parent: kreta_api_project
    resource: Kreta\Bundle\ProjectBundle\Controller\IssuePriorityController
