# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
#### SECURITY ####
    kreta_project.voter.project:
        class: %kreta_project.security_project_voter.class%
        public: false
        tags:
           - { name: security.voter }

#### UPLOADER ####
    kreta_project.uploader.image_project:
        class: %kreta_media.uploader_media.class%
        arguments:
            - @kreta_project.uploader_filesystem.image_project
    kreta_project.uploader_filesystem.image_project:
        class: Gaufrette\Filesystem
        factory:
            - @knp_gaufrette.filesystem_map
            - get
        arguments:
            - %projects.image.uploader.filesystem%
