# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

services:
#### FORM HANDLER ####
    kreta_project.form_handler.project:
        class: %kreta_project.form_project_handler.class%
        arguments: [@form.factory, @doctrine.orm.entity_manager, @event_dispatcher, @kreta_media.factory.media, @kreta_project.uploader.image_project]

#### SECURITY ####
    kreta_project.voter.project:
        class: %kreta_project.security_project_voter.class%
        public: false
        tags:
           - { name: security.voter }

#### UPLOADER ####
    kreta_project.uploader.image_project:
        class: %kreta_media.uploader_media.class%
        arguments: [@kreta_project.uploader_filesystem.image_project]
    kreta_project.uploader_filesystem.image_project:
        class: Gaufrette\Filesystem
        factory_service: knp_gaufrette.filesystem_map
        factory_method: get
        arguments: [%projects.image.uploader.filesystem%]
