# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

services:
    kreta_api.command.create_client:
        class: Kreta\Bundle\ApiBundle\Command\CreateClientCommand
        calls:
            - [setContainer, ['@service_container']]

    kreta_api.listener.json_exception:
        class: Kreta\Bundle\ApiBundle\EventListener\JsonExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 200 }

    kreta_api.subscriber.media_url:
        class: Kreta\Bundle\ApiBundle\EventSubscriber\MediaUrlSubscriber
        arguments: [@router]
        tags:
            - { name: jms_serializer.event_subscriber }

    kreta_api.form_handler.project:
        class: Kreta\Bundle\ApiBundle\Form\Handler\ProjectHandler
        arguments: [@form.factory, @doctrine.orm.entity_manager, @event_dispatcher, @kreta_media.factory.media, @kreta_core.uploader.image_project]

    kreta_api.form_handler.issue:
        class: Kreta\Bundle\ApiBundle\Form\Handler\IssueHandler
        arguments: [@form.factory, @doctrine.orm.entity_manager, @event_dispatcher]

    kreta_api.form_handler.status:
        class: Kreta\Bundle\ApiBundle\Form\Handler\StatusHandler
        arguments: [@form.factory, @doctrine.orm.entity_manager, @event_dispatcher, @kreta_media.factory.media, @kreta_core.uploader.image_project]
