# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.identity_access.http_action.user:
        class: Kreta\IdentityAccess\Infrastructure\Symfony\HttpAction\UserAction
        arguments:
            - "@security.token_storage"

    kreta.identity_access.http_action.users_by_ids:
        class: Kreta\IdentityAccess\Infrastructure\Symfony\HttpAction\UsersByIdsAction
        arguments:
            - "@kreta.identity_access.query_bus"

    kreta.identity_access.http_action.search:
        class: Kreta\IdentityAccess\Infrastructure\Symfony\HttpAction\SearchAction
        arguments:
            - "@kreta.identity_access.query_bus"

    kreta.identity_access.http_action.edit_profile:
        class: Kreta\IdentityAccess\Infrastructure\Symfony\HttpAction\EditProfileAction
        arguments:
            - "@security.token_storage"
            - "@form.factory"
            - "@bengor_user.user.command_bus"
            - "@lexik_jwt_authentication.encoder.default"
            - "@bengor_user.user.provider"

    kreta.identity_access.http_action.enable:
        class: Kreta\IdentityAccess\Infrastructure\Symfony\HttpAction\EnableAction
        arguments:
            - "@kreta.identity_access.command_bus"
