# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

parameters:
#### CLASSES ####
    kreta_core.class_comment: Kreta\CoreBundle\Entity\Comment
    kreta_core.class_issue: Kreta\CoreBundle\Entity\Issue
    kreta_core.class_label: Kreta\CoreBundle\Entity\Label
    kreta_core.class_project: Kreta\CoreBundle\Entity\Project
    kreta_core.class_user: Kreta\CoreBundle\Entity\User

    kreta_core.factory_class_comment: Kreta\CoreBundle\Factory\CommentFactory
    kreta_core.factory_class_issue: Kreta\CoreBundle\Factory\IssueFactory
    kreta_core.factory_class_label: Kreta\CoreBundle\Factory\LabelFactory
    kreta_core.factory_class_project: Kreta\CoreBundle\Factory\ProjectFactory
    kreta_core.factory_class_user: Kreta\CoreBundle\Factory\UserFactory

    kreta_core.repository_class_comment: Kreta\CoreBundle\Repository\CommentRepository
    kreta_core.repository_class_issue: Kreta\CoreBundle\Repository\IssueRepository
    kreta_core.repository_class_label: Kreta\CoreBundle\Repository\LabelRepository
    kreta_core.repository_class_project: Kreta\CoreBundle\Repository\ProjectRepository
    kreta_core.repository_class_user: Kreta\CoreBundle\Repository\UserRepository

services:
#### FACTORIES ####
    kreta_core.factory_comment:
        class: %kreta_core.factory_class_comment%
    kreta_core.factory_issue:
        class: %kreta_core.factory_class_issue%
    kreta_core.factory_label:
        class: %kreta_core.factory_class_label%
    kreta_core.factory_project:
        class: %kreta_core.factory_class_project%
    kreta_core.factory_user:
        class: %kreta_core.factory_class_user%

#### REPOSITORIES ####
    kreta_core.repository_comment:
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        class: %kreta_core.repository_class_comment%
        arguments: [%kreta_core.class_comment%]
    kreta_core.repository_issue:
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        class: %kreta_core.repository_class_issue%
        arguments: [%kreta_core.class_issue%]
    kreta_core.repository_label:
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        class: %kreta_core.repository_class_label%
        arguments: [%kreta_core.class_label%]
    kreta_core.repository_project:
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        class: %kreta_core.repository_class_project%
        arguments: [%kreta_core.class_project%]
    kreta_core.repository_user:
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        class: %kreta_core.repository_class_user%
        arguments: [%kreta_core.class_user%]
