# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

Kreta\Component\Workflow\Model\Status:
    exclusion_policy: ALL
    relations:
        -
            rel: self
            href:
                route: get_workflow_status
                parameters:
                    workflowId: expr(object.getWorkflow().getId())
                    statusId: expr(object.getId())
                absolute: true
            exclusion:
                groups: [statusList, status]
        -
            rel: statuses
            href:
                route: get_workflow_statuses
                parameters:
                    workflowId: expr(object.getWorkflow().getId())
                absolute: true
            exclusion:
                groups: [statusList, status]
        -
            rel: workflow
            href:
                route: get_workflow
                parameters:
                    workflowId: expr(object.getWorkflow().getId())
                absolute: true
            exclusion:
                groups: [statusList, status]
    properties:
        id:
            expose: true
            groups: [projectList, project, issueList, issue, statusList, status]
        color:
            expose: true
            groups: [projectList, project, issueList, issue, statusList, status]
        name:
            expose: true
            groups: [projectList, project, issueList, issue, statusList, status]
        project:
            expose: true
            groups: []
        type:
            expose: true
            groups: [projectList, project, issueList, issue, statusList, status]
        transitions:
            expose: true
            groups: [projectList, project, statusList, status]

