# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

Kreta\Component\TimeTracking\Model\TimeEntry:
    exclusion_policy: ALL
    relations:
        -
            rel: self
            href:
                route: get_issues_time_entry
                parameters:
                    issueId: expr(object.getIssue().getId())
                    timeEntryId: expr(object.getId())
                absolute: true
            exclusion:
                groups: [timeEntryList, timeEntry]
        -
            rel: timeEntries
            href:
                route: get_issues_time_entries
                parameters:
                    issueId: expr(object.getIssue().getId())
                absolute: true
            exclusion:
                groups: [timeEntryList, timeEntry]
        -
            rel: issues
            href:
                route: get_issues
                absolute: true
            exclusion:
                groups: [timeEntryList, timeEntry]
    properties:
        id:
            expose: true
            groups: [timeEntryList, timeEntry]
        dateReported:
            expose: true
            groups: [timeEntryList, timeEntry]
        description:
            expose: true
            groups: [timeEntryList, timeEntry]
        issue:
            expose: true
            groups: []
        timeSpent:
            expose: true
            groups: [timeEntryList, timeEntry]
