# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Notification\Model\Notification:
    type: entity
    repositoryClass: Kreta\Component\Notification\Repository\NotificationRepository
    table: notification
    id:
        id:
            type: string
            generator:
                strategy: UUID
    fields:
        date:
            type: datetime
        description:
            type: text
        read:
            column: is_read # Avoids using reserved SQL word (read)
            type: boolean
        resourceUrl:
            type: string
        title:
            type: string
            length: 140
        type:
            type: string
            length: 50
        webUrl:
            type: string
    manyToOne:
        project:
            targetEntity: Kreta\Component\Project\Model\Interfaces\ProjectInterface
            joinColumn:
                name: project_id
                referencedColumnName: id
        user:
            targetEntity: Kreta\Component\User\Model\Interfaces\UserInterface
            joinColumn:
                name: user_id
                referencedColumnName: id
