# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.identity_access.action.user:
        class: Kreta\IdentityAccess\Infrastructure\Ui\Http\Action\UserAction
        arguments:
            - "@security.authorization_checker"
            - "@security.token_storage"

    kreta.identity_access.action.invite:
        class: Kreta\IdentityAccess\Infrastructure\Ui\Http\Action\InviteAction
        arguments:
            - "@form.factory"
            - "@bengor_user.user.command_bus"

    kreta.identity_access.action.resend_invitation:
        class: Kreta\IdentityAccess\Infrastructure\Ui\Http\Action\ResendInvitationAction
        arguments:
            - "@form.factory"
            - "@bengor_user.user.command_bus"

    kreta.identity_access.action.sign_up:
        class: Kreta\IdentityAccess\Infrastructure\Ui\Http\Action\SignUpAction
        arguments:
            - "@bengor_user.user.by_invitation_token_query"
            - "@form.factory"
            - "@kreta.identity_access.command_bus"
            - "@lexik_jwt_authentication.encoder.default"
            - "@bengor_user.user.command_bus"
