# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.identity_access.views.twig.loader:
        class: Twig_Loader_Filesystem
        arguments:
            - ["%kernel.root_dir%/../Ui/Views/Twig"]
        tags:
            - { name: twig.loader }
