# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

imports:
    - { resource: ../../../../../../../parameters.yml }
    - { resource: security.yml }
    - { resource: services/, type: directory }

parameters:
    identity_access_locale: en_US
    jwt_token_lifetime: 31556926    # 1 year

framework:
    secret: "%identity_access_secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: false }
    templating:
        engines: ['twig']
    default_locale: "%identity_access_locale%"
    translator: { fallbacks: ["%identity_access_locale%"] }
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        handler_id: session.handler.native_file
        name: kretasession
        save_path: "%kernel.root_dir%/../../../../../../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~

twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"

doctrine:
    dbal:
        driver: pdo_mysql
        host: "%identity_access_database_host%"
        port: "%identity_access_database_port%"
        dbname: "%identity_access_database_name%"
        user: "%identity_access_database_user%"
        password: "%identity_access_database_password%"
        charset: UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            IdentityAccess:
                mapping: true
                type: xml
                is_bundle: false
                dir: "%kernel.root_dir%/../../Persistence/Doctrine/ORM/User/SymfonyMapping/"
                prefix: 'Kreta\IdentityAccess\Domain\Model\User'

doctrine_migrations:
    dir_name: "%kernel.root_dir%/../../Persistence/Doctrine/Migrations"
    namespace: Kreta\IdentityAccess\Infrastructure\Persistence\Doctrine\Migrations
    table_name: migration_versions
    name: Kreta Identity Access Migrations

swiftmailer:
    transport: "%identity_access_mailer_transport%"
    host: "%identity_access_mailer_host%"
    username: "%identity_access_mailer_user%"
    password: "%identity_access_mailer_password%"
    port: "%identity_access_mailer_port%"
    encryption: "%identity_access_mailer_encryption%"
    spool: { type: memory }

knp_gaufrette:
    stream_wrapper: ~
    adapters:
        image_adapter:
            local:
                directory: "%kernel.root_dir%/../../Ui/Http/Symfony/public/images"
                create: true
    filesystems:
        image_filesystem:
            adapter: image_adapter

ben_gor_file:
    file_class:
        image:
            class: Kreta\IdentityAccess\Domain\Model\User\Image
            storage: gaufrette
            upload_destination: image_filesystem

ben_gor_user:
    user_class:
        user:
            class: Kreta\IdentityAccess\Domain\Model\User\User
            data_transformer: Kreta\IdentityAccess\Application\DataTransformer\UserDTODataTransformer
            firewall: main
            use_cases:
                security:
                    enabled: false
                    api_enabled: true
                sign_up:
                    enabled: false
                    api_enabled: true
                    api_type: with_confirmation
                change_password:
                    enabled: false
                    api_enabled: true
                    api_type: by_request_remember_password
                remove:
                    enabled: false
            routes:
                security:
                    jwt:
                        path: /auth/token
                sign_up:
                    api_name: kreta_identity_access_sign_up_with_confirmation
                    api_path: /register
                enable:
                    api_name: kreta_identity_access_enable
                    api_path: /enable
                change_password:
                    api_name: kreta_identity_access_change_password
                    api_path: /change-password
                request_remember_password:
                    api_name: kreta_identity_access_request_remember_password
                    api_path: /remember-password

lexik_jwt_authentication:
    private_key_path: "%kernel.root_dir%/../../../../../../var/jwt/private.pem"
    public_key_path: "%kernel.root_dir%/../../../../../../var/jwt/public.pem"
    pass_phrase: "%identity_access_jwt_key_pass_phrase%"
    token_ttl: "%jwt_token_lifetime%"
    user_identity_field: email

nelmio_cors:
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: [Content-Type, Origin, X-Custom-Auth, x-requested-with, x-requested-by, Authorization]
            allow_methods: [GET, POST, PUT, DELETE, OPTIONS]
            max_age: 3600

old_sound_rabbit_mq:
    connections:
        default:
            host: "%identity_access_rabbitmq_host%"
            port: "%identity_access_rabbitmq_port%"
            user: "%identity_access_rabbitmq_user%"
            password: "%identity_access_rabbitmq_password%"
            vhost: '/'
            lazy: true
            connection_timeout: 3
            read_write_timeout: 3
            keepalive: false
            heartbeat: 0
    producers:
        asynchronous_events:
            connection: default
            exchange_options:
                name: asynchronous_events
                type: direct

simple_bus_asynchronous:
    object_serializer_service_id: kreta.identity_access.serialization.simple_bus.async_event_serializer

simple_bus_rabbit_mq_bundle_bridge:
    events:
        producer_service_id: old_sound_rabbit_mq.asynchronous_events_producer
