# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

kreta_identity_access_invite:
    path: /invite
    defaults:
        _controller: "kreta.identity_access.http_action.invite:__invoke"
    methods:
        - POST

kreta_identity_access_resend_invitation:
    path: /resend-invitation
    defaults:
        _controller: "kreta.identity_access.http_action.resend_invitation:__invoke"
    methods:
        - POST

kreta_identity_access_sign_up_by_invitation:
    path: /register
    defaults:
        _controller: "kreta.identity_access.http_action.sign_up:__invoke"
    methods:
        - POST

ben_gor_user:
    resource: '@BenGorUserBundle/Resources/config/routing/all.yml'

kreta_identity_access_user:
    path: /user
    defaults:
        _controller: "kreta.identity_access.http_action.user:__invoke"
    methods:
        - GET

