# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Mutation:
    type: object
    config:
        fields:
            createOrganization:
                builder: Mutation
                builderConfig:
                    inputType: CreateOrganizationInput
                    payloadType: CreateOrganizationPayload
                    mutateAndGetPayload: "@=mutation('create_organization', [args.offsetGet('input')])"
            editOrganization:
                builder: Mutation
                builderConfig:
                    inputType: EditOrganizationInput
                    payloadType: EditOrganizationPayload
                    mutateAndGetPayload: "@=mutation('edit_organization', [args.offsetGet('input')])"
            createProject:
                builder: Mutation
                builderConfig:
                    inputType: CreateProjectInput
                    payloadType: CreateProjectPayload
                    mutateAndGetPayload: "@=mutation('create_project', [args.offsetGet('input')])"
            editProject:
                builder: Mutation
                builderConfig:
                    inputType: EditProjectInput
                    payloadType: EditProjectPayload
                    mutateAndGetPayload: "@=mutation('edit_project', [args.offsetGet('input')])"
            createTask:
                builder: Mutation
                builderConfig:
                    inputType: CreateTaskInput
                    payloadType: CreateTaskPayload
                    mutateAndGetPayload: "@=mutation('create_task', [args.offsetGet('input')])"
            editTask:
                builder: Mutation
                builderConfig:
                    inputType: EditTaskInput
                    payloadType: EditTaskPayload
                    mutateAndGetPayload: "@=mutation('edit_task', [args.offsetGet('input')])"
            changeTaskProgress:
                builder: Mutation
                builderConfig:
                    inputType: ChangeTaskProgressInput
                    payloadType: ChangeTaskProgressPayload
                    mutateAndGetPayload: "@=mutation('change_task_progress', [args.offsetGet('input')])"
