# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# This implements the following type system shorthand:
#
#   type Project {
#     id: ID!
#     created_on: String!
#     name: String!
#     organization: Organization!
#     owners: [Owner!]!
#     slug: String!
#     updatedOn: String!
#   }

Project:
    type: object
    config:
        description: "A project inside Kreta ecosystem"
        fields:
            id:
                type: "ID!"
                description: "The id of the project."
            created_on:
                type: "String!"
                description: "The created on of the project."
            name:
                type: "String!"
                description: "The name of the project."
            organization:
                type: "Organization!"
                description: "The organization to which the project belongs."
            slug:
                type: "String!"
                description: "The slug of the project."
            updated_on:
                type: "String!"
                description: "The updated on of the project."
        interfaces: [Node]
