# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.notifier.repository.inbox.user:
        class: Kreta\Notifier\Infrastructure\Persistence\EventStore\Inbox\EventStoreUserRepository
        arguments:
            - '@kreta.notifier.event_store.redis'

    kreta.notifier.repository.inbox_user_read:
        class: ONGR\ElasticsearchBundle\Service\Repository
        arguments:
            - "@es.manager.default"
            - Kreta\Notifier\Infrastructure\Projection\ReadModel\Inbox\Elasticsearch\User
