# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

Kreta\Component\Project\Model\Priority:
    type: entity
    repositoryClass: Kreta\Component\Project\Repository\PriorityRepository
    table: priority
    id:
        id:
            type: string
            generator:
                strategy: UUID
    fields:
        name:
            type: string
            length: 20
    manyToOne:
        project:
            targetEntity: Kreta\Component\Project\Model\Interfaces\ProjectInterface
            inversedBy: issueTypes
            joinColumn:
                name: project_id
                referencedColumnName: id
