# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Project\Model\Project:
    type: entity
    repositoryClass: Kreta\Component\Project\Repository\ProjectRepository
    table: project
    id:
        id:
            type: string
            generator:
                strategy: UUID
    fields:
        name:
            type: string
            length: 140
        slug:
            type: string
            length: 140
    manyToOne:
        organization:
            targetEntity: Kreta\Component\Organization\Model\Interfaces\OrganizationInterface
            inversedBy: projects
            joinColumn:
                name: organization_id
                referencedColumnName: id
                onDelete: CASCADE
            cascade: ['persist', 'remove']
        workflow:
            targetEntity: Kreta\Component\Workflow\Model\Interfaces\WorkflowInterface
            inversedBy: projects
            joinColumn:
                name: workflow_id
                referencedColumnName: id
                onDelete: CASCADE
            cascade: ['persist', 'remove']
    oneToOne:
        image:
            targetEntity: Kreta\Component\Media\Model\Interfaces\MediaInterface
            joinColumn:
                name: image
                referencedColumnName: id
            cascade: ['persist', 'remove']
    oneToMany:
        issues:
            targetEntity: Kreta\Component\Issue\Model\Interfaces\IssueInterface
            mappedBy: project
            cascade: ['persist', 'remove']
        labels:
            targetEntity: Kreta\Component\Project\Model\Interfaces\LabelInterface
            mappedBy: project
            cascade: ['persist', 'remove']
        participants:
            targetEntity: Kreta\Component\Project\Model\Interfaces\ParticipantInterface
            mappedBy: project
            cascade: ['persist', 'remove']
        issuePriorities:
            targetEntity: Kreta\Component\Project\Model\Interfaces\IssuePriorityInterface
            mappedBy: project
            cascade: ['persist', 'remove']
