# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Organization\Model\Organization:
    exclusion_policy: ALL
    relations:
        -
            rel: self
            href:
                route: get_organization
                parameters:
                    organizationId: expr(object.getId())
                absolute: 0
            exclusion:
                groups: [organizationList, organization]
        -
            rel: organizations
            href:
                route: get_organizations
                absolute: 0
            exclusion:
                groups: [organizationList, organization]
        -
            rel: projects
            href:
                route: get_projects
                absolute: 0
            exclusion:
                groups: [organizationList, organization]
    properties:
        id:
            expose: true
            groups:
                - organizationList
                - organization
                - organizationPrivate
                - organizationParticipantList
                - organizationParticipant
                - projectList
                - project
                - projectPrivate
        image:
            expose: true
            groups:
                - organizationList
                - organization
                - organizationPrivate
                - projectList
                - project
                - projectPrivate
        name:
            expose: true
            groups:
                - organizationList
                - organization
                - organizationPrivate
                - organizationParticipantList
                - organizationParticipant
                - projectList
                - project
                - projectPrivate
        participants:
            expose: true
            groups:
                - organizationPrivate
        projects:
            expose: true
            groups: []
        slug:
            expose: true
            groups:
                - organizationList
                - organization
                - organizationPrivate
                - organizationParticipantList
                - organizationParticipant
                - projectList
                - project
                - projectPrivate
