# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta_organization.factory.participant:
        class: '%kreta_organization.factory_participant.class%'
        arguments:
            - '%kreta_organization.participant.class%'
    kreta_organization.factory.organization:
        class: '%kreta_organization.factory_organization.class%'
        arguments:
            - '%kreta_organization.organization.class%'
            - '@kreta_organization.factory.participant'
            - '@kreta_media.factory.media'
            - '@kreta_organization.uploader.image_organization'
