# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
#### HANDLERS ####
    kreta_organization.form_handler.organization:
        class: %kreta_organization.form_handler.organization.class%
        parent: kreta_core.form_handler.handler
        arguments:
            - Kreta\Component\Organization\Form\Type\OrganizationType
            - '@kreta_media.factory.media'
            - '@kreta_organization.uploader.image_organization'
    kreta_organization.form_handler.participant:
        parent: kreta_core.form_handler.handler
        arguments:
            - Kreta\Component\Organization\Form\Type\ParticipantType

#### TYPES ####
    kreta_organization.form_type.organization:
        class: %kreta_organization.form_type.organization.class%
        arguments:
            - %kreta_organization.organization.class%
            - '@kreta_organization.factory.organization'
            - '@security.token_storage'
        tags:
            - { name: form.type }
    kreta_organization.form_type.participant:
        class: %kreta_organization.form_type.participant.class%
        arguments:
            - %kreta_organization.participant.class%
            - '@kreta_organization.factory.participant'
            - '@security.token_storage'
        tags:
            - { name: form.type }
    kreta_organization.form_type.role:
        class: %kreta_organization.form_type.role.class%
        tags:
            - { name: form.type }
