# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
#### SECURITY ####
    kreta_organization.voter.organization:
        class: %kreta_organization.security_organization_voter.class%
        public: false
        tags:
           - { name: security.voter }

#### UPLOADER ####
    kreta_organization.uploader.image_organization:
        class: %kreta_media.uploader_media.class%
        arguments:
            - '@kreta_organization.uploader_filesystem.image_organization'
    kreta_organization.uploader_filesystem.image_organization:
        class: Gaufrette\Filesystem
        factory:
            - '@knp_gaufrette.filesystem_map'
            - get
        arguments:
            - %organizations.image.uploader.filesystem%
