# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.task_manager.graph_ql.mutation.create_organization:
        class: Kreta\TaskManager\Infrastructure\Symfony\GraphQl\Mutation\Organization\CreateOrganizationMutation
        arguments:
            - "@security.token_storage"
            - "@kreta.task_manager.command_bus"
            - "@kreta.task_manager.graph_ql.query_resolver.organization_of_id"
        tags:
            - { name: overblog_graphql.mutation, alias: "create_organization", method: "execute" }

    kreta.task_manager.graph_ql.mutation.edit_organization:
        class: Kreta\TaskManager\Infrastructure\Symfony\GraphQl\Mutation\Organization\EditOrganizationMutation
        arguments:
            - "@security.token_storage"
            - "@kreta.task_manager.command_bus"
            - "@kreta.task_manager.graph_ql.query_resolver.organization_of_id"
        tags:
            - { name: overblog_graphql.mutation, alias: "edit_organization", method: "execute" }
