# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

-
    name: "Build hosts file"
    lineinfile:
        dest: /etc/hosts
        line: "127.0.0.1 {{ kreta.domains.identity_access }} {{ kreta.domains.task_manager }} {{ kreta.domains.composite_ui }} www.{{ kreta.domains.composite_ui }}"
