# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Bundle\CoreBundle\Model\AccessToken:
    type: entity
    table: access_token
    id:
        id:
            type: string
            generator:
                strategy: UUID
    manyToOne:
        client:
            targetEntity: Kreta\Bundle\CoreBundle\Model\Client
            joinColumn:
                name: client_id
                referencedColumnName: id
                nullable: false
        user:
            targetEntity: Kreta\Component\User\Model\Interfaces\UserInterface
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: true
