# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

Kreta\Component\Core\Model\User:
    type: entity
    repositoryClass: Kreta\Component\Core\Repository\UserRepository
    table: user
    id:
        id:
            type: string
            generator:
                strategy: UUID
    fields:
        bitbucketAccessToken:
            column: bitbucket_access_token
            type: string
            length: 255
            nullable: true
        bitbucketId:
            column: bitbucket_id
            type: string
            length: 255
            nullable: true
        createdAt:
            column: created_at
            type: datetime
        firstName:
            column: first_name
            type: string
            length: 100
            nullable: true
        githubAccessToken:
            column: github_access_token
            type: string
            length: 255
            nullable: true
        githubId:
            column: githubId
            type: string
            length: 255
            nullable: true
        lastName:
            column: last_name
            type: string
            length: 100
            nullable: true

    oneToMany:
        assignedIssues:
            targetEntity: Kreta\Component\Core\Model\Interfaces\IssueInterface
            mappedBy: assignee
        comments:
            targetEntity: Kreta\Component\Core\Model\Interfaces\CommentInterface
            mappedBy: writtenBy
        participants:
            targetEntity: Kreta\Component\Core\Model\Interfaces\ParticipantInterface
            mappedBy: user
        reportedIssues:
            targetEntity: Kreta\Component\Core\Model\Interfaces\IssueInterface
            mappedBy: reporter

    attributeOverride:
        email:
            type: string
            length: 255
            nullable: true

        emailCanonical:
            column: email_canonical
            type: string
            length: 255
            nullable: true

        username:
            type: string
            length: 255
            nullable: true

        usernameCanonical:
            column: username_canonical
            type: string
            length: 255
            nullable: true
