# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.task_manager.data_transformer.member_dto:
        class: Kreta\TaskManager\Application\DataTransformer\Organization\MemberDTODataTransformer

    kreta.task_manager.data_transformer.organization_dto:
        class: Kreta\TaskManager\Application\DataTransformer\Organization\OrganizationDTODataTransformer
        arguments:
            - "@kreta.task_manager.data_transformer.member_dto"
