# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
#### FORM HANDLER ####
    kreta_issue.form_handler.issue:
        parent: kreta_core.form_handler.handler
        arguments:
            - Kreta\Component\Issue\Form\Type\IssueType

#### TYPES ####
    kreta_issue.form_type.issue:
        class: %kreta_issue.form_type.issue.class%
        arguments:
            - %kreta_issue.issue.class%
            - @kreta_issue.factory.issue
            - @security.token_storage
            - null
            - null
            - @kreta_project.form_type.label
        tags:
            - { name: form.type }
