# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    kreta_issue.issue.class: Kreta\Component\Issue\Model\Issue
    kreta_issue.resolution.class: Kreta\Component\Issue\Model\Resolution

    kreta_issue.factory_issue.class: Kreta\Component\Issue\Factory\IssueFactory
    kreta_issue.factory_resolution.class: Kreta\Component\Issue\Factory\ResolutionFactory

    kreta_issue.repository_issue.class: Kreta\Component\Issue\Repository\IssueRepository
    kreta_issue.repository_resolution.class: Kreta\Component\Issue\Repository\ResolutionRepository

    kreta_issue.form_type.issue.class: Kreta\Component\Issue\Form\Type\IssueType

    kreta_issue.state_machine_issue.class: Kreta\Component\Issue\StateMachine\IssueStateMachine
    kreta_issue.security_issue_voter.class: Kreta\Bundle\IssueBundle\Security\Authorization\Voter\IssueVoter
