# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta_user.manager.oauth_manager:
        class: '%kreta_user.manager.oauth_manager.class%'
        arguments:
            - '@fos_oauth_server.client_manager'
            - '@fos_oauth_server.server'
            - '%oauth.web.client_secret%'
