# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    kreta_user.user.class: Kreta\Component\User\Model\User

    kreta_user.factory_user.class: Kreta\Component\User\Factory\UserFactory

    kreta_user.repository_user.class: Kreta\Component\User\Repository\UserRepository

    kreta_user.form_user_handler.class: Kreta\Component\User\Form\Handler\UserHandler

    kreta_user.invitation.email.template: KretaUserBundle::invitation.html.twig

    kreta_user.form_type.invitation.class: Kreta\Component\User\Form\Type\InvitationType
    kreta_user.form_type.profile.class: Kreta\Component\User\Form\Type\ProfileType
    kreta_user.form_type.registration.class: Kreta\Component\User\Form\Type\RegistrationType
