# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

parameters:
    kreta_notification.notification.class: Kreta\Component\Notification\Model\Notification

    kreta_notification.factory_notification.class: Kreta\Component\Notification\Factory\NotificationFactory
    kreta_notification.event_subscriber_doctrine.class: Kreta\Component\Notification\EventSubscriber\DoctrineEventSubscriber
    kreta_notification.notifier_registry.class: Kreta\Component\Notification\Notifier\Registry\NotifierRegistry
    kreta_notification.notifiable_event_registry.class: Kreta\Component\Notification\NotifiableEvent\Registry\NotifiableEventRegistry
    kreta_notification.repository_notification.class: Kreta\Component\Notification\Repository\NotificationRepository

services:
    kreta_notification.factory.notification:
        class: %kreta_notification.factory_notification.class%
        arguments: [%kreta_notification.notification.class%]

    kreta_notification.doctrine_event_subscriber:
        class: %kreta_notification.event_subscriber_doctrine.class%
        arguments: [@kreta_notification.notifiable_event_registry, @kreta_notification.notifier_registry]
        tags:
            - { name: doctrine.event_subscriber }

    #Notifiers
    kreta_notification.notifier_registry:
        class: %kreta_notification.notifier_registry.class%

    kreta_notification.notifier.email:
        class: Kreta\Component\Notification\Notifier\EmailNotifier
        arguments: [@mailer]
        tags:
            - { name: kreta_notification.notifier, label: email }

    #Notifiable events
    kreta_notification.notifiable_event_registry:
        class: %kreta_notification.notifiable_event_registry.class%

    kreta_notification.notifiable_event.issue:
        class: Kreta\Component\Notification\NotifiableEvent\IssueEvents
        arguments: [@kreta_notification.factory.notification, @router]
        tags:
            - { name: kreta_notification.notifiable_event, label: issue }

    kreta_notification.repository.notification:
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        class: %kreta_notification.repository_notification.class%
        arguments: [%kreta_notification.notification.class%]



