# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

Kreta\Component\VCS\Model\Commit:
    exclusion_policy: ALL
    relations:
        -
            rel: commits
            href:
                route: get_issues_commits
                parameters:
                    issueId: expr(object.getIssuesRelated()[0].getId())
                absolute: true
            exclusion:
                groups: [commitList]
        -
            rel: branches
            href:
                route: get_issues_branches
                parameters:
                    issueId: expr(object.getIssuesRelated()[0].getId())
                absolute: true
            exclusion:
                groups: [commitList]
        -
            rel: repositories
            href:
                route: get_projects_repositories
                parameters:
                    projectId: expr(object.getIssuesRelated()[0].getProject().getId())
                absolute: true
            exclusion:
                groups: [commitList]
        -
            rel: issue
            href:
                route: get_issue
                parameters:
                    issueId: expr(object.getIssuesRelated()[0].getId())
                absolute: true
            exclusion:
                groups: [commitList]
    properties:
        id:
            expose: true
            groups: [commitList, repositoryList]
        author:
            expose: true
            groups: [commitList, repositoryList]
        message:
            expose: true
            groups: [commitList, repositoryList]
        sha:
            expose: true
            groups: [commitList, repositoryList]
        url:
            expose: true
            groups: [commitList, repositoryList]
        branch:
            expose: true
            groups: [commitList, repositoryList]
        issuesRelated:
            expose: true
            groups: []
