# This file belongs to Kreta.
# The source code of application includes a LICENSE file
# with all information about license.
#
# @author benatespina <benatespina@gmail.com>
# @author gorkalaucirica <gorka.lauzirika@gmail.com>

kreta_api_project:
    type: rest
    resource: Kreta\Bundle\ProjectBundle\Controller\ProjectController

kreta_api_label:
    type: rest
    parent: kreta_api_project
    resource: Kreta\Bundle\ProjectBundle\Controller\LabelController

kreta_api_participant:
    type: rest
    parent: kreta_api_project
    resource: Kreta\Bundle\ProjectBundle\Controller\ParticipantController

kreta_api_issue_priority:
    type: rest
    parent: kreta_api_project
    resource: Kreta\Bundle\ProjectBundle\Controller\IssuePriorityController
