# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

imports:
    - { resource: ../../../../../../../parameters.yml }
    - { resource: security.yml }
    - { resource: services/, type: directory }

parameters:
    notifier_locale: en

framework:
    secret: "%notifier_secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: false }
    templating:
        engines: ['twig']
    default_locale: "%notifier_locale%"
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        handler_id: session.handler.native_file
        name: kretasession
        save_path: "%kernel.root_dir%/../../../../../../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~

twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"

doctrine:
    dbal:
        driver: pdo_mysql
        host: "%notifier_database_host%"
        port: "%notifier_database_port%"
        dbname: "%notifier_database_name%"
        user: "%notifier_database_user%"
        password: "%notifier_database_password%"
        charset: UTF8
#        types:
#            user_id:
#                class: Kreta\Notifier\Infrastructure\Persistence\Doctrine\DBAL\User\Types\UserIdType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            SharedKernelIdentity:
                mapping: true
                type: xml
                is_bundle: false
                dir: "%kernel.root_dir%/../../../../../../../SharedKernel/src/Kreta/SharedKernel/Infrastructure/Persistence/Doctrine/ORM/Identity/SymfonyMapping/"
                prefix: 'Kreta\SharedKernel\Domain\Model\Identity'
            NotifierNotification:
                mapping: true
                type: xml
                is_bundle: false
                dir: "%kernel.root_dir%/../../Projection/Projector/Doctrine/ORM/Notification/SymfonyMapping/"
                prefix: 'Kreta\Notifier\Infrastructure\Projection\ReadModel'

doctrine_migrations:
    dir_name: "%kernel.root_dir%/../../Persistence/Doctrine/Migrations"
    namespace: Kreta\Notifier\Infrastructure\Persistence\Doctrine\Migrations
    table_name: migration_versions
    name: Kreta Notifier Migrations

swiftmailer:
    transport: "%notifier_mailer_transport%"
    host: "%notifier_mailer_host%"
    username: "%notifier_mailer_user%"
    password: "%notifier_mailer_password%"
    spool: { type: memory }

nelmio_cors:
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: [Content-Type, Origin, X-Custom-Auth, x-requested-with, x-requested-by, Authorization]
            allow_methods: [GET, POST, PUT, DELETE, OPTIONS]
            max_age: 3600

#old_sound_rabbit_mq:
#    connections:
#        default:
#            host: "%notifier_rabbitmq_host%"
#            port: "%notifier_rabbitmq_port%"
#            user: "%notifier_rabbitmq_user%"
#            password: "%notifier_rabbitmq_password%"
#            vhost: '/'
#            lazy: true
#            connection_timeout: 3
#            read_write_timeout: 3
#            keepalive: false
#            heartbeat: 0
#    consumers:
#        asynchronous_events:
#            connection: default
#            exchange_options:
#                name: asynchronous_events
#                type: direct
#            queue_options:
#                name: asynchronous_events
#            callback: kreta.notifier.rabbit_mq_bundle.user_registered

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%notifier_redis_dsn%"
