# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

overblog_graphql_endpoint:
    resource: "@OverblogGraphQLBundle/Resources/config/routing/graphql.yml"

kreta_front:
    path: /{page}
    defaults:
        _controller: "kreta.task_manager.controller.default:indexAction"
    requirements:
        page: ".+"

kreta_front_index:
    path: /
    defaults:
        _controller: "kreta.task_manager.controller.default:indexAction"
