# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.task_manager.query_handler.organization_of_id:
        class: Kreta\TaskManager\Application\Query\Organization\OrganizationOfIdHandler
        arguments:
            - "@kreta.task_manager.repository.organization"
            - "@kreta.task_manager.data_transformer.organization_dto"
        tags:
            -
                name: query_handler
                handles: Kreta\TaskManager\Application\Query\Organization\OrganizationOfIdQuery
